name: "Fork Sync"
on:
  schedule:
    - cron:  '0 */2 * * *'
  workflow_dispatch:
jobs:
  sync-master:
    runs-on: ubuntu-latest
    name: "Sync from n8n-io/n8n@master"
    steps:
    - name: "Checkout: master"
      uses: actions/checkout@v2
      with:
        ref: master
        token: ${{ github.token }}
    - name: "Update: master"
      id: sync-master
      uses: aormsby/Fork-Sync-With-Upstream-action@v3.4.1
      with:
        domain: 'github.com'
        upstream_repository: n8n-io/n8n
        upstream_branch: master
        target_branch: master
        git_pull_args: --ff-only
        # git_push_args: --force
    - name: Timestamp
      run: date
